# Generated by Django 5.0.7 on 2024-07-18 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=100)),
                ('resolution', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vgscdb_id', models.CharField(max_length=100)),
                ('synonyms', models.TextField()),
                ('description', models.TextField()),
                ('orgnism', models.TextField()),
                ('pdb_id', models.CharField(max_length=100)),
                ('uniprot_id', models.CharField(max_length=100)),
                ('source', models.ManyToManyField(to='vgscdb.source')),
            ],
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vgscdb_id', models.CharField(max_length=100)),
                ('pubchem_cid', models.CharField(max_length=100)),
                ('iupac_name', models.TextField()),
                ('molecular_formula', models.TextField()),
                ('molecular_weight', models.TextField()),
                ('ic50ec50', models.TextField()),
                ('Bindingsite', models.TextField()),
                ('orgnism', models.TextField()),
                ('uniprot_name', models.TextField()),
                ('uniprot_id', models.TextField()),
                ('smiles', models.TextField()),
                ('inchi', models.TextField()),
                ('inchi_key', models.TextField()),
                ('article_doi', models.TextField()),
                ('pmid', models.TextField()),
                ('authors', models.TextField()),
                ('institution', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vgscdb.category')),
                ('target', models.ManyToManyField(to='vgscdb.target')),
            ],
        ),
    ]
