# Generated by Django 5.0.7 on 2024-07-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgscdb', '0002_remove_compound_category_remove_target_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='synonyms',
            field=models.TextField(),
        ),
    ]
