# Generated by Django 5.0.7 on 2024-07-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vgscdb', '0003_alter_target_synonyms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='synonyms',
        ),
    ]
