# Generated by Django 5.0.7 on 2024-07-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgscdb', '0004_remove_target_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='Bindingsite',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='article_doi',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='authors',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='ic50ec50',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='inchi',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='inchi_key',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='institution',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='iupac_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='molecular_formula',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='molecular_weight',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='orgnism',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='pmid',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='pubchem_cid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='compound',
            name='smiles',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='uniprot_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='uniprot_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='vgscdb_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
