# Generated by Django 5.0.7 on 2024-07-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgscdb', '0006_compound_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='pdb_id',
            field=models.TextField(blank=True),
        ),
    ]
